# terms.Term { #formulae.terms.Term }

```python
terms.Term(*components)
```

Model term.

Terms are made of one or more components. Components are instances of
[Variable](`formulae.terms.Variable`) or [Call](`formulae.terms.Call`). Terms with only one
component are known as main effects and terms with more than one component are known as
interaction effects. The order of the interaction is given by the number of components in the
term.

## Parameters {.doc-section .doc-section-parameters}

<code>[**components**]{.parameter-name} [:]{.parameter-annotation-sep} [[Variable](`formulae.terms.variable.Variable`) or [Call](`formulae.terms.call.Call`)]{.parameter-annotation} [ = ]{.parameter-default-sep} [()]{.parameter-default}</code>

:   Atomic components of a term.

## Attributes {.doc-section .doc-section-attributes}

<code>[**data**]{.parameter-name} [:]{.parameter-annotation-sep} [[np](`numpy`).[ndarray](`numpy.ndarray`)]{.parameter-annotation}</code>

:   The values associated with the term as they go into the design matrix.

<code>[**kind**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   Indicates the type of the term. Can be one of `"numeric"`, `"categoric"`, or `"interaction"`.

<code>[**name**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   The name of the term as it was originally written in the model formula.

## Methods

| Name | Description |
| --- | --- |
| [eval_new_data](#formulae.terms.Term.eval_new_data) | Evaluates the term with new data. |
| [get_component](#formulae.terms.Term.get_component) | Returns a component by name. |
| [set_data](#formulae.terms.Term.set_data) | Obtains and stores the final data object related to this term. |
| [set_type](#formulae.terms.Term.set_type) | Set type of the components in the term. |

### eval_new_data { #formulae.terms.Term.eval_new_data }

```python
terms.Term.eval_new_data(data)
```

Evaluates the term with new data.

Calls `.eval_new_data()` method on each component in the term and combines the results
appropriately.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**data**]{.parameter-name} [:]{.parameter-annotation-sep} [[pd](`pandas`).[DataFrame](`pandas.DataFrame`)]{.parameter-annotation}</code>

:   The data frame where variables are taken from

#### Returns {.doc-section .doc-section-returns}

<code>[**result**]{.parameter-name} [:]{.parameter-annotation-sep} [[np](`numpy`).[array](`numpy.array`)]{.parameter-annotation}</code>

:   The values resulting from evaluating this term using the new data.

### get_component { #formulae.terms.Term.get_component }

```python
terms.Term.get_component(name)
```

Returns a component by name.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**name**]{.parameter-name} [:]{.parameter-annotation-sep} [[str](`str`)]{.parameter-annotation}</code>

:   The name of the component to return.

#### Returns {.doc-section .doc-section-returns}

<code>[**component**]{.parameter-name} [:]{.parameter-annotation-sep} [[Variable](`formulae.terms.variable.Variable`) or [Call](`formulae.terms.call.Call`)]{.parameter-annotation}</code>

:   The component with name `name`.

### set_data { #formulae.terms.Term.set_data }

```python
terms.Term.set_data(spans_intercept)
```

Obtains and stores the final data object related to this term.

Calls `.set_data()` method on each component in the term. Then, it uses the `.data`
attribute on each of them to build `self.data`.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**spans_intercept**]{.parameter-name} [:]{.parameter-annotation-sep} [[dict](`dict`) or [bool](`bool`)]{.parameter-annotation}</code>

:   Indicates whether categorical components span the intercept. When it is a dictionary, keys are component names and values indicate whether each component spans the intercept. When it is a boolean, the same value is used for all components.

### set_type { #formulae.terms.Term.set_type }

```python
terms.Term.set_type(data, env)
```

Set type of the components in the term.

Calls `.set_type()` method on each component in the term. For those components of class
[Variable](`formulae.terms.Variable`) it only passes the data mask. For
[Call](`formulae.terms.Call`) objects it also passes the evaluation environment.

#### Parameters {.doc-section .doc-section-parameters}

<code>[**data**]{.parameter-name} [:]{.parameter-annotation-sep} [[pd](`pandas`).[DataFrame](`pandas.DataFrame`)]{.parameter-annotation}</code>

:   The data frame where variables are taken from

<code>[**env**]{.parameter-name} [:]{.parameter-annotation-sep} [[Environment](`Environment`)]{.parameter-annotation}</code>

:   The environment where values and functions are taken from.